### ISSUE TITLE
feature request: 支持linux系统

### ISSUE THREAD

**Issue by Zhou-Shilin** [H2Sxxa/Rosa#17]
如题，能否提供一个linux版本的rosa？
哪怕是脚本无gui的也行

我是一个ubuntu用户，希望使用MCreator为我的Bukkit插件编写一个配套的客户端Forge模组，但是在创建工作区时遇到了网络问题。尝试使用[FClash](https://github.com/Fclash/Fclash)，在开启System Proxy的情况下(FTP端口与Sockets端口保持一致)，浏览器访问正常但是MCreator疑似不走代理。已经尝试过修改`/WorkSpaceRoot/PojectName/gradle.properties`文件并添加以下配置，可以用但是每次MCreator都会刷新该文件导致每次都需要卡点在刷新后但是读配置前那几秒钟内修改文件，十分麻烦…

同时我也想使用到rosa的其他功能 :)

**Comment by H2Sxxa** [comment]
尝试过TUN模式吗

Linux当时没有支持的原因之一是没有Proxifier for Linux......

Flutter本身就是跨平台而生的，编译出Linux版本问题不大，不过可能是个花瓶......

就算有，适配起来也很麻烦，~~Rosa与Windows注册表打了很多交道，跨平台很难实现~~

~~如果你需要TUI版本，或许可以去复兴一下MCreator-Setup，看你Repo里有py项目~~

**Comment by Zhou-Shilin** [comment]
> 尝试过TUN模式吗
> 
> Linux当时没有支持的原因之一是没有Proxifier for Linux......
> 
> Flutter本身就是跨平台而生的，编译出Linux版本问题不大，不过可能是个花瓶......
> 
> 就算有，适配起来也很麻烦，~Rosa与Windows注册表打了很多交道，跨平台很难实现~
> 
> ~如果你需要TUI版本，或许可以去复兴一下MCreator-Setup，看你Repo里有py项目~

tun试过了不行
~至于mcr-setup…我这技术能力不行（）~
