### ISSUE TITLE
feat: 通过转移assets文件夹来达到加速构建的方法

### ISSUE THREAD

**Issue by cdc12345** [H2Sxxa/Rosa#3]
MCreator_GRADLE_USER_HOME : %USERPROFILE%\\.mcreator\gradle (默认,其实mcreator也改不了:) )

如果rosa能够知道用户的mc安装目录

那么rosa就能够转移mc安装目录下的assets文件夹到

在GRADLE目录下 caches\forge_gradle (相对路径) caches\fabric-loom (fabric用处不大-.-)

相关的windows命令 [mklink](https://learn.microsoft.com/zh-cn/windows-server/administration/windows-commands/mklink)用于创造软链接

**Comment by cdc12345** [comment]
linux不知道你打不打算支持,所以没扯

**Comment by H2Sxxa** [comment]
> linux不知道你打不打算支持,所以没扯

没有相关环境测试，要支持后期再说

**Comment by H2Sxxa** [comment]
有空了，稍微看了一下，先说说我的2个问题

- 这个软件还需面向非mcreator用户，两者gradle目录不同，不过这个应该易于解决
- mc游戏资源如何定位，这边可以交由用户选择文件夹，但这会增加风险，还有如果没有mc是不是要从镜像拉取再导入

**Comment by cdc12345** [comment]
> 有空了，稍微看了一下，先说说我的2个问题
> 
>     * 这个软件还需面向非mcreator用户，两者gradle目录不同，不过这个应该易于解决
> 
>     * mc游戏资源如何定位，这边可以交由用户选择文件夹，但这会增加风险，还有如果没有mc是不是要从镜像拉取再导入

镜像拉取得话也许可以试试看

**Comment by cdc12345** [comment]
关于mc游戏资源的定位

官方默认:AppData\Roaming\.minecraft

第三方启动器就不好定位了,改了更不好找(

**Comment by cdc12345** [comment]
![图片](https://github.com/H2Sxxa/Rosa/assets/63762187/7c98e7a9-a0b1-43d6-8432-98556051963e)
然后关于assets构建得话,如果我们能够修改这上面得那个final变量就能够加速

**Comment by H2Sxxa** [comment]
> ![图片](https://github.com/H2Sxxa/Rosa/assets/63762187/7c98e7a9-a0b1-43d6-8432-98556051963e)
> 然后关于assets构建得话,如果我们能够修改这上面得那个final变量就能够加速

这个IDF有相关的实现，可以看看它的setting.gradle，用的比较hack的方法，但这个仅限于fg，要是fg的fork，例如rfg，这个方法就无效了

我的目的是想要找到一个通法，之前用过m itm来拦截asset，但会有系统代理和证书问题。。。

**Comment by H2Sxxa** [comment]
> ![图片](https://github.com/H2Sxxa/Rosa/assets/63762187/7c98e7a9-a0b1-43d6-8432-98556051963e)
> 然后关于assets构建得话,如果我们能够修改这上面得那个final变量就能够加速

这个IDF有相关的实现，可以看看它的setting.gradle，用的比较hack的方法，但这个仅限于fg，要是fg的fork，例如rfg，这个方法就无效了

我的目的是想要找到一个通法，之前用过m itm来拦截asset，但会有系统代理和证书问题。。。
