### ISSUE TITLE
feat: 重写ForgeGradle部分类并编译重新注入Jar加速构建

### ISSUE THREAD

**Issue by H2Sxxa** [H2Sxxa/Rosa#5]
如题

Jar相当于Zip，只要拥有编译好的class，操作不成问题

**Comment by H2Sxxa** [comment]
备选Maven
bmclapi2.bangbang93.com/maven
crystal.app.lss233.com/repositories/minecraft
download.mcbbs.net/maven

备选assets
bmclapi2.bangbang93.com
download.mcbbs.net

推荐使用mcbbs源，更加可靠

**Comment by H2Sxxa** [comment]
计划支持列表
Forge
https://github.com/GTNewHorizons/RetroFuturaGradle
https://github.com/MinecraftForge/ForgeGradle

Fabric不考虑，loom可以修改gradle.properties

**Comment by cdc12345** [comment]
仓库找不到了(

**Comment by cdc12345** [comment]
forgeGradle:
https://github.com/MinecraftForge/ForgeGradle/blob/8e240cdab8ea3ef112f2835d53ab93ae7ec67ac2/src/common/java/net/minecraftforge/gradle/common/util/Utils.java#L88
这地方很有意思

**Comment by H2Sxxa** [comment]
fg你打算支持哪些版本，大概看了一下，似乎不同版本都写的不大一样

还是说直接弄个超集（不过不同版本可能会出现包引入问题）

**Comment by cdc12345** [comment]
直接最新版本好了(

**Comment by cdc12345** [comment]
另外,lss的镜像源坏了,不过备用链接可以用(

**Comment by H2Sxxa** [comment]
建议用mcbbs的

**Comment by H2Sxxa** [comment]
最好就支持一下这⑤个（
FG23
FG30
FG40
FG50
FG60

**Comment by H2Sxxa** [comment]
FG23不支持也可以，反正有RFG

**Comment by cdc12345** [comment]
这个Utils类的导入太多了,很容易出问题,我找其他方法.(

**Comment by H2Sxxa** [comment]
关于Jar的定位，我似乎找到了2个位置，后者的包体几乎是前者的三倍，有点搞不明白应该对谁下手
.gradle\caches\modules-2\files-2.1\<package name>\<project name>\<version>\<hash>\....jar
.gradle\caches\jars-9\<hash>\....jar

**Comment by H2Sxxa** [comment]
> > 关于Jar的定位，我似乎找到了2个位置，后者的包体几乎是前者的三倍，有点搞不明白应该对谁下手 .gradle\caches\modules-2\files-2.1....jar .gradle\caches\jars-9....jar
> 
> 我是在files-2.1里找到forgegradle的jar的
> 
> 另外,jars-9的hash码我始终找不到得到方式,我等会去翻一下gradle的源码吧(

不拿hash也可以，我可以彻底遍历来定位，就是不知道要patch哪一个

**Comment by H2Sxxa** [comment]
另外就是说Patch之后运行会不会被检查hash

**Comment by cdc12345** [comment]
> 另外就是说Patch之后运行会不会被检查hash

这是个问题,gradle我翻了一下用户文档,只说是贡献缓存,没提hash的方法是啥

**Comment by H2Sxxa** [comment]
使用RFG测试，无论是修改jar9还是file2中的jar都没有任何效果😇
想要搞明白这个，必须先搞明白gradle插件如何引入，暂时等待进一步研究🤔

**Comment by H2Sxxa** [comment]
经过测试以及反编译问题查明出在java编译的处理，所有的常量引用会变为常量，导致实际上与Constants.class没有什么关系
gradle插件引入顺序: 将依赖下载入 file-2.1 -> 在jar-9中创建运行使用的jar -> 使用jar-9中的jar进行gradle任务
感谢cdc查明gradle运行时使用的jar文件路径

**Comment by cdc12345** [comment]
直接删掉jars-9(管他n还是什么) ,让gradle重新起飞(

**Comment by H2Sxxa** [comment]
反正也是类似于缓存，字词（

**Comment by H2Sxxa** [comment]
收集一些信息
RFG：使用Constants起到下载功能的类（Patch对象）
 - com/gtnewhorizons/retrofuturagradle/minecraft/MinecraftTasks
 - com/gtnewhorizons/retrofuturagradle/minecraft/downloadTasks
FG的话应该也是类似这2个

**Comment by cdc12345** [comment]
> 收集一些信息 RFG：使用Constants起到下载功能的类（Patch对象）
> 
>     * com/gtnewhorizons/retrofuturagradle/minecraft/MinecraftTasks
> 
>     * com/gtnewhorizons/retrofuturagradle/minecraft/downloadTasks
>       FG的话应该也是类似这2个

还没成年吧,喝不了酒吧,真好喝)

**Comment by H2Sxxa** [comment]
暂时完成，等待class完成即可发布rc2

**Comment by H2Sxxa** [comment]
打包jar与jar打包jar有所出入，等待修复

**Comment by H2Sxxa** [comment]
压缩就算改了level还是有问题，同时因为Dart的zlibencoder暂时没那么好用，我估计得引入7-zip或者Jar来处理压缩

Jar需要java runtime，故舍弃，将会采用7zip来进行压缩

（那我还tm用个p的archive）


#12

**Comment by H2Sxxa** [comment]
暂时完成，RFG已经过测试可用，等待其他FG的Feedback
