### ISSUE TITLE
bug: Constants.class未遵循class文件规范

### ISSUE THREAD

**Issue by cdc12345** [H2Sxxa/Rosa#7]
![图片](https://github.com/H2Sxxa/Rosa/assets/63762187/8aadb551-df91-47cd-a44d-0388592e23cf)

**Comment by H2Sxxa** [comment]
毕竟是用VSC文本编辑器改的，我想也会有问题（

**Comment by H2Sxxa** [comment]
另外，我在想有没有通过ASM，反射以及Mixin来修改Gradle插件的可能性

**Comment by cdc12345** [comment]
> 另外，我在想有没有通过ASM，反射以及Mixin来修改Gradle插件的可能性

ASM确实可以(

**Comment by cdc12345** [comment]
修复好了(

**Comment by H2Sxxa** [comment]
ok，感谢修复

**Comment by cdc12345** [comment]
eclipse配合jadx(

**Comment by cdc12345** [comment]
毕竟直接pull下来可以构建到天荒地老(
