### ISSUE TITLE
feat: 应用图标

### ISSUE THREAD

**Issue by H2Sxxa** [H2Sxxa/Rosa#9]
欢迎大家来此issue贡献你的work

**Comment by cdc12345** [comment]
没人啊)

**Comment by H2Sxxa** [comment]
> 没人啊)

实在不行我闲下来自己画（

**Comment by H2Sxxa** [comment]
![rosa_icon-modified](https://github.com/H2Sxxa/Rosa/assets/88923783/991919b3-0d9b-48a5-b724-0c5069296e56)
根据Thbwiki的图标改过来的，反正都是花（

**Comment by H2Sxxa** [comment]
暂时就用这个了，谁有心画可以@我reopen这个issue
